---
# HTTPD Deployment Playbook

- hosts: awswebservers
  become: true

  tasks:
  - name: Include ks_apache
    include_role: 
      name: ks_apache
    vars: 
      ks_apache_webserver: "{{ webserver_name }}"
    with_items:
      - webserverone.kris
      - webservertwo.kris
    loop_control:
      loop_var: webserver_name
